### ISSUE TITLE
Comparison with PAL?

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#1]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/1)) by Anthony Clark (Bitbucket: [anthonyjclark](https://bitbucket.org/%7B9adbb19d-7f74-45cc-8768-1ab1d5845c29%7D/)).**

----------------------------------------
Hello,

I would like to know how this effort compares to existing software. For example, how does it compare to how Gazebo currently handles physics engines? And how does it compare to [PAL](http://www.adrianboeing.com/pal/index.html)? [This document](https://osrfoundation.atlassian.net/wiki/spaces/GAZ/pages/659926/Ignition+Physics) only partially explains how this will be different than Gazebo's current approach.

Please let me know if there is a better forum for this sort of discussion.

**Comment by chapulina** [comment]
@anthonyjclark, I'll close this issue because https://community.gazebosim.org/ is a better place for this kind of conversation. Feel free to take this conversation there.
