### ISSUE TITLE
ign-physics getting-started tutorials

### ISSUE THREAD

**Issue by anindex** [ignitionrobotics/ign-physics#103]
Some planning for getting-started tutorials:

- Introduction:
  - Overview and motivation of ign-physics
  - What are ign-physics purposes and where it is in the Ignition Robotics framework (optionally draw a framework graph highlighting ign-physics)
  - Currently supported physics engines and corresponding features overview (link to [plugin description](https://github.com/ignitionrobotics/ign-physics/blob/master/tutorials/03_physics_plugins.md))
  - Roadmap of future plans of ign-physics, a potential timeline of certain features.
- Installation: Tweaking and improving [current installation guide](https://github.com/ignitionrobotics/ign-physics/blob/master/tutorials/02_installation.md) for Dome release.
- Switching physics plugins tutorial
  - Describe ways to switch physics engine from ign-gazebo

**Comment by claireyywang** [comment]
closing since all PRs are merged
- https://github.com/ignitionrobotics/ign-physics/pull/104
- https://github.com/ignitionrobotics/ign-physics/pull/105
- https://github.com/ignitionrobotics/ign-physics/pull/106
