### ISSUE TITLE
Test examples on CI

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-physics#109]
The [examples](https://github.com/ignitionrobotics/ign-physics/tree/master/examples) are not tested on CI, so it's easy to forget to update them. We should be testing them on CI like other libraries do:

* [ign-gazebo](https://github.com/ignitionrobotics/ign-gazebo/blob/master/test/integration/examples_build.cc)
* [ign-gui](https://github.com/ignitionrobotics/ign-gui/blob/master/test/integration/ExamplesBuild_TEST.cc)
* [ign-math](https://github.com/ignitionrobotics/ign-math/blob/master/test/integration/ExamplesBuild_TEST.cc)

I think at least some of the libraries above require the library to be installed before running these tests, which is not ideal. I believe there are ways to work around this though, by setting environment variables, or installing, but to a local directory.

**Comment by ahcorde** [comment]
Already merged
