### ISSUE TITLE
Heightmap support for DART

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-physics#156]
DART supports heightmap geometries. We should tie that into Ignition Physics.

This is needed by https://github.com/ignitionrobotics/ign-gazebo/issues/237.

It can make use of this PR adding heightmaps to SDF: https://github.com/osrf/sdformat/pull/388

See [gazebo::physics::DARTHeightmapShape](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/physics/dart/DARTHeightmapShape.cc) as reference.

**Comment by scpeters** [comment]
I've started work on this in the following branch, but I haven't finished the `CustomHeightmapShape` constructor and probably need to change the parameters in the `AttachHeightmapShape` API (I had initially copied the mesh API)

* https://github.com/ignitionrobotics/ign-physics/compare/ign-physics2...scpeters:heightmap2

**Comment by scpeters** [comment]
still need to port the code for creating the heightmap shape:

* https://github.com/osrf/gazebo/blob/gazebo11_11.3.0/gazebo/physics/dart/DARTHeightmapShapePrivate.hh#L73-L82
* https://github.com/osrf/gazebo/blob/gazebo11_11.3.0/gazebo/physics/dart/DARTHeightmapShape.cc#L56-L68

**Comment by chapulina** [comment]
Rebased @scpeters 's branch onto `main` and fixed compilation in https://github.com/ignitionrobotics/ign-physics/compare/main...chapulina/4/heightmap
