### ISSUE TITLE
Speed up compilation

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#20]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/20)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
# Summary

It takes a long time to compile the code.

# Motivation

Speed up development by reducing compile time.

# Describe alternatives you've considered

Deal with it (what we are currently doing).

# Additional context

I think @mxgrey has some additional context.

**Comment by scpeters** [comment]
this has been resolved in ign-physics2
