### ISSUE TITLE
Segmentation Fault (ODE Internal Error)

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#22]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/22)) by Michael Carroll (Bitbucket: [Michael Carroll](https://bitbucket.org/%7B17dbbc15-cbc0-42f0-a985-cde9061c78a0%7D/), GitHub: [mjcarroll](https://github.com/mjcarroll)).**

----------------------------------------
# Segmentation Fault \(ODE Internal Error\)

When trying to perform some benchmark work, I discovered a segmentation fault in ign-physics:

```
ODE INTERNAL ERROR 1: assertion &#34;bNormalizationResult&#34; failed in _dNormalize4() [odemath.h:42]
```

# Steps to Reproduce

1. Create a world with a 5 x 5 x 5 cube of unit spheres, randomly perturbed slightly in the x and y axis.

    1. \(Or use this one: [https://gist.github.com/mjcarroll/fab4c63ed3231c170ffdb549ff605770#file-spheres\_5\_5-sdf](https://gist.github.com/mjcarroll/fab4c63ed3231c170ffdb549ff605770#file-spheres_5_5-sdf)\)
    
2. Execute with `ign gazebo`

**Expected behavior:** It shouldn’t crash.

**Actual behavior:** It does

**Reproduces how often:** 100%

# Versions

ign-gazebo2 \(blueprint\) source build

**Additional Information**

I have a more complete backtrace here, snipped to the relevant bits: [https://gist.github.com/mjcarroll/fab4c63ed3231c170ffdb549ff605770#file-backtrace](https://gist.github.com/mjcarroll/fab4c63ed3231c170ffdb549ff605770#file-backtrace)

**Comment by azeey** [comment]
I believe this has been fixed by https://github.com/azeey/dart/pull/6

**Comment by traversaro** [comment]
Thanks a lot @azeey, that was quite a big source of problems!
