### ISSUE TITLE
Extend contact data

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#24]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/24)) by Diego Ferigo (Bitbucket: [dgferigo](https://bitbucket.org/%7B994b27a5-7d6d-42b2-8aa7-2ea82fbe7bf6%7D/)).**

----------------------------------------
The [GetContacts.hh](https://github.com/ignitionrobotics/ign-physics/blob/39bc98ce499bdd400e1e23a66c29bbd16adda352/include/ignition/physics/GetContacts.hh) features allows to extract some basic information from contacts, such as bodyA bodyB and contact point in world frame.

Is there any update to what discussed in [PR67](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/pull-requests/67/acropolis-getcontactsfromlaststep-feature/diff)? The structure [GetContacts.hh#74](https://github.com/ignitionrobotics/ign-physics/blob/39bc98ce499bdd400e1e23a66c29bbd16adda352/include/ignition/physics/GetContacts.hh#lines-74) seems the place where to possibly add normal and magnitude. @azeey  @scpeters 

‌

**Comment by azeey** [comment]
Closed by #40
