### ISSUE TITLE
Reopen pull request to reduce symbol load

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#28]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/28)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Reopen [pull request #136](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/pull-requests/136) once we're migrated to GitHub.

**Comment by scpeters** [comment]
I think this was fixed by #41
