### ISSUE TITLE
Reopen pull request to restore detached BodyNodes to original skeleton

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#29]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/29)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
We didn't finish revising [pull request #104](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/pull-requests/104) before the GitHub migration freeze date, so this issue is to remind to reopen a pull request from branch `detach_joint_feature_detach_to_skeleton`. There are still some outstanding comments related to the naming scheme for detached joints and how to handle links with `/` characters in their names. Perhaps the original skeleton name could be stored in the [dartsim JointInfo struct in Base.hh](https://github.com/ignitionrobotics/ign-physics/blob/8f0d8ce3229f53fbf4e05cb0273530169e6d9fef/dartsim/src/Base.hh#L62) and the original name stored in a similar manner to the [ShapeInfo class](https://github.com/ignitionrobotics/ign-physics/blob/8f0d8ce3229f53fbf4e05cb0273530169e6d9fef/dartsim/src/Base.hh#L71:73).

Unresolved comments:

* https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/pull-requests/104/detachjoint-try-to-restore-bodynodes-to/activity#comment-144557904
* https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/pull-requests/104/detachjoint-try-to-restore-bodynodes-to/activity#comment-144559098

**Comment by azeey** [comment]
https://github.com/ignitionrobotics/ign-physics/pull/42 closes this
