### ISSUE TITLE
Ball rolling down an incline achieves warp speed

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#7]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/7)) by Addisu Z. Taddese (Bitbucket: [azeey](https://bitbucket.org/%7B9d7fdc68-d270-4080-bf03-4df0d0dbf635%7D/), GitHub: [azeey](https://github.com/azeey)).**

The original report had attachments: [rolling_shapes.sdf](https://osrf-migration.github.io/ignition-gh-pages/data/repositories/ignitionrobotics/ign-physics/issues/7/attachments/rolling_shapes.sdf)

----------------------------------------
As seen in the gif, the ball starts rolling on an incline (a large box inclined ~30 degrees) and after a few seconds, it shoots off in the process crashing ign-gazebo.

![ign-physics-warp-speed.gif](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/5q9rMzd/images/897293863-ign-physics-warp-speed.gif)

**Comment by azeey** [comment]
Fixed by https://github.com/azeey/dart/pull/5
