### ISSUE TITLE
Benchmark Performance 

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-physics#88]
Run performance tests for TPE and compare against DART.

some ideas of what to measure:
* time to run one iteration in physics system in ign-gazebo
* time to step a world in ign-physics
* time to perform collision detection
* RTF
* memory usage

ideas for test worlds
* large world with simple shapes / meshes
* large word with crowds of actors

We can consider using tools like the profiler from ign-common to get remotery graphs of cpu usage. To do this, we'll need to add profiling points throughout the code, see [profiler tutorial](https://ignitionrobotics.org/api/common/3.1/profiler.html)

other useful tools include:
* [flamegraphs](http://www.brendangregg.com/flamegraphs.html) - cpu uage
* [heaptrack](https://github.com/KDE/heaptrack) - for memory usage

**Comment by claireyywang** [comment]
report on google doc https://docs.google.com/document/d/16PfhDd2eSl-QdJFPY52-nV8zDLnYfyFAbX8wHCkRjO4/edit?usp=sharing
